# Generated by Django 5.2.3 on 2026-04-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(blank=True, upload_to='skills/'),
        ),
    ]
